version: '3.9'
services:
  postgresql:
    image: postgres:12.18-bullseye
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: login
      POSTGRES_PASSWORD: pass




